<Project>

  <PropertyGroup>
    <ExternalCertificateId>3PartySHA2</ExternalCertificateId>
    <DetachedSignatureCertificateId>LinuxSign500180PGP</DetachedSignatureCertificateId>
    <UseDotNetCertificate>true</UseDotNetCertificate>
  </PropertyGroup>

  <ItemGroup>
    <ItemsToSign Remove="@(ItemsToSign)" />
  </ItemGroup>

  <ItemGroup>
    <ItemsToSign Include="$(SignableSourceBuiltAssets)" />
  </ItemGroup>

  <ItemGroup>
    <!-- We don't need to code sign .js files because they are not used in Windows Script Host -->
    <FileExtensionSignInfo Update=".js" CertificateName="None" />

    <!-- Specify assets that should be signed with a detached signature -->
    <FileSignInfo Include="@(DetachedSignatureAssets->'%(Filename)%(Extension)')" CertificateName="$(DetachedSignatureCertificateId)" />
    <CertificatesSignInfo Include="$(DetachedSignatureCertificateId)" DetachedSignature="true" />
    <!-- Need to find a way to not unpack these files in SignTool -->
    <NoUnpackSignInfo Include="@(DetachedSignatureAssets->'%(Filename)%(Extension)')" />

    <!-- Sign 3rd party files that end up in the artifacts -->
    <FileSignInfo Include="Humanizer.dll" CertificateName="$(ExternalCertificateId)" />
    <FileSignInfo Include="Mono.Cecil.dll" CertificateName="$(ExternalCertificateId)" />
    <FileSignInfo Include="Mono.Cecil.Mdb.dll" CertificateName="$(ExternalCertificateId)" />
    <FileSignInfo Include="Mono.Cecil.Pdb.dll" CertificateName="$(ExternalCertificateId)" />
    <FileSignInfo Include="Mono.Cecil.Rocks.dll" CertificateName="$(ExternalCertificateId)" />
    <FileSignInfo Include="Newtonsoft.Json.dll" CertificateName="$(ExternalCertificateId)" />
    <FileSignInfo Include="Valleysoft.DockerCredsProvider.dll" CertificateName="$(ExternalCertificateId)" />

    <!--
        Skip warning on files that are marked as 3rd party but have .NET copyright:
        "Copyright © .NET Foundation and Contributors" or ".NET Foundation and Contributors" 
    -->
    <ItemsToSkip3rdPartyCheck Include="mscorlib.dll" />
    <ItemsToSkip3rdPartyCheck Include="netstandard.dll" />
  </ItemGroup>

</Project>
