# This is the dotnet/dotnet pipeline that is triggered every weekday at midnight (00:00 UTC) for "main" and when changes are pushed to all other branches.

schedules:
- cron: '0 0 * * Mon-Fri'
  displayName: Weekday midnight build
  branches:
    include:
    - main
  batch: true

trigger:
  batch: true
  branches:
   exclude:
   - main

pr: none

stages:
- stage: Stage1
  jobs:
  - job: Job1
    displayName: "Stage 1"
    steps:
    - script: echo "Stage 1"
      displayName: "Stage 1"

- stage: Stage2
  jobs:
  - job: Job2
    steps:
    - script: echo "Stage 2"
      displayName: "Stage 2"