name: 'Check VMR Versions'

on:
  pull_request:
    paths:
      - eng/common/**/*
      - eng/Version.Details.xml
      - eng/Versions.props

permissions:
  pull-requests: read

jobs:
  check-vmr-versions:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Version Validation Tests
        script: |
          .dotnet/dotnet build eng/version-validation.proj \
            /p:DotNetRootDirectory=$(pwd) \
            /p:PullRequestTargetBranch=${{ github.event.pull_request.base.ref }} \
            /p:PullRequestTitle="${{ github.event.pull_request.title }}"
